CREATE COLUMN TABLE "DWC_DEMO"."Employees" ("EMPLOYEEID" NVARCHAR(10) NOT NULL , "NAME_FIRST" VARCHAR(40), "NAME_MIDDLE" VARCHAR(40), "NAME_LAST" VARCHAR(40), "NAME_INITIALS" NVARCHAR(10), "SEX" NVARCHAR(1), "LANGUAGE" NVARCHAR(2), "PHONENUMBER" NVARCHAR(30), "EMAILADDRESS" NVARCHAR(255), "LOGINNAME" NVARCHAR(12), "ADDRESSID" NVARCHAR(10), "VALIDITY_STARTDATE" DATE CS_DAYDATE, "VALIDITY_ENDDATE" DATE CS_DAYDATE, PRIMARY KEY ("EMPLOYEEID", "VALIDITY_ENDDATE")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON TABLE "DWC_DEMO"."Employees" is 'Exmployee data';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."EMPLOYEEID" is 'Employee ID';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."NAME_FIRST" is 'First name';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."NAME_MIDDLE" is 'Middle name';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."NAME_LAST" is 'Last name';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."NAME_INITIALS" is 'Name initials';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."SEX" is 'Sex';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."LANGUAGE" is 'Language';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."PHONENUMBER" is 'Phone number';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."EMAILADDRESS" is 'Email address';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."LOGINNAME" is 'Login name';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."ADDRESSID" is 'Address ID';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."VALIDITY_STARTDATE" is 'Validity start date';
COMMENT ON COLUMN "DWC_DEMO"."Employees"."VALIDITY_ENDDATE" is 'Validity end date'