CREATE COLUMN TABLE "DWC_DEMO"."ProductCategories" ("PRODCATEGORYID" NVARCHAR(2) NOT NULL , "CREATEDBY" NVARCHAR(10), "CREATEDAT" DATE CS_DAYDATE, PRIMARY KEY ("PRODCATEGORYID")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON TABLE "DWC_DEMO"."ProductCategories" is 'Product categories';
COMMENT ON COLUMN "DWC_DEMO"."ProductCategories"."PRODCATEGORYID" is 'Product category ID';
COMMENT ON COLUMN "DWC_DEMO"."ProductCategories"."CREATEDBY" is 'Created by';
COMMENT ON COLUMN "DWC_DEMO"."ProductCategories"."CREATEDAT" is 'Created at date'