CREATE COLUMN TABLE "DWC_DEMO"."BusinessPartners" ("PARTNERID" NVARCHAR(10) NOT NULL , "PARTNERROLE" NVARCHAR(3), "EMAILADDRESS" NVARCHAR(255), "PHONENUMBER" NVARCHAR(30), "FAXNUMBER" NVARCHAR(30), "WEBADDRESS" NVARCHAR(1024), "ADDRESSID" NVARCHAR(10), "COMPANYNAME" NVARCHAR(80), "LEGALFORM" NVARCHAR(10), "CREATEDBY" NVARCHAR(10), "CREATEDAT" DATE CS_DAYDATE, "CHANGEDBY" NVARCHAR(10), "CHANGEDAT" DATE CS_DAYDATE, "CURRENCY" NVARCHAR(5), PRIMARY KEY ("PARTNERID")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON TABLE "DWC_DEMO"."BusinessPartners" is 'Business Partners';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."PARTNERID" is 'Partner ID';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."PARTNERROLE" is 'Partner nole';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."EMAILADDRESS" is 'Email nddress';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."PHONENUMBER" is 'Phone number';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."FAXNUMBER" is 'Fax number';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."WEBADDRESS" is 'Web address';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."ADDRESSID" is 'Address ID';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."COMPANYNAME" is 'Company name';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."LEGALFORM" is 'Legal form';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."CREATEDBY" is 'Created by';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."CREATEDAT" is 'Created at date';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."CHANGEDBY" is 'Changed by';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."CHANGEDAT" is 'Changed at date';
COMMENT ON COLUMN "DWC_DEMO"."BusinessPartners"."CURRENCY" is 'Currency key'