CREATE COLUMN TABLE "DWC_DEMO"."Addresses" ("ADDRESSID" NVARCHAR(10) NOT NULL , "STREET" NVARCHAR(60), "CITY" VARCHAR(40), "POSTALCODE" NVARCHAR(10), "BUILDING" NVARCHAR(10), "COUNTRY" NVARCHAR(3), "REGION" NVARCHAR(4), "ADDRESSTYPE" NVARCHAR(2), "VALIDITY_STARTDATE" DATE CS_DAYDATE, "VALIDITY_ENDDATE" DATE CS_DAYDATE, "LATITUDE" DOUBLE CS_DOUBLE, "LONGITUDE" DOUBLE CS_DOUBLE, PRIMARY KEY ("ADDRESSID")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON TABLE "DWC_DEMO"."Addresses" is 'Adresses';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."ADDRESSID" is 'Address ID';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."STREET" is 'Street';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."CITY" is 'City';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."POSTALCODE" is 'Postal code';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."BUILDING" is 'Building';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."COUNTRY" is 'Country';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."REGION" is 'Region';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."ADDRESSTYPE" is 'Address type';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."VALIDITY_STARTDATE" is 'Start date';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."VALIDITY_ENDDATE" is 'Start date';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."LATITUDE" is 'Latitude';
COMMENT ON COLUMN "DWC_DEMO"."Addresses"."LONGITUDE" is 'Longitude'